kitronik_servo_lite.setDistancePerSecond(10)
basic.showIcon(IconNames.Happy)
let strip = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)
strip.showRainbow(1, 360)
basic.forever(function () {
    kitronik_servo_lite.driveForwards(10)
    basic.pause(500)
    kitronik_servo_lite.turnLeft(65)
    basic.pause(500)
})
